apiVersion: v1
data:
  DB_NAME: {{ .Values.configMap.DB_NAME }}
  DB_TABLE: {{ .Values.configMap.DB_TABLE }}
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.configMap.name }}
  namespace: {{ .Release.Namespace }}
