apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.app.name }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          ports:
            - containerPort: {{ .Values.app.containerPort }}
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.app.env.MYSQL_USER.secretKeyRef.name }}
                  key: {{ .Values.app.env.MYSQL_USER.secretKeyRef.key }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.app.env.MYSQL_PASSWORD.secretKeyRef.name }}
                  key: {{ .Values.app.env.MYSQL_PASSWORD.secretKeyRef.key }}
            - name: MYSQL_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.app.env.MYSQL_DB.configMapKeyRef.name }}
                  key: {{ .Values.app.env.MYSQL_DB.configMapKeyRef.key }}                  
            - name: MYSQL_HOST
              value: {{ .Release.Name }}-{{ .Values.dbService.name }}.{{ .Release.Namespace }}.svc.cluster.local              
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.app.env.API_KEY.secretKeyRef.name }}
                  key: {{ .Values.app.env.API_KEY.secretKeyRef.key }}
          resources:
            requests:
              cpu: {{ .Values.app.resources.requests.cpu }}
              memory: {{ .Values.app.resources.requests.memory }}
            limits:
              cpu: {{ .Values.app.resources.limits.cpu }}
              memory: {{ .Values.app.resources.limits.memory }}
