apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Values.db.volumeMounts.mysqlData.name }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
{{- range .Values.pvc.accessMode }}  
    - {{ . }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage | quote }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  volumeMode: {{ .Values.pvc.volumeMode }}
  volumeName: {{ .Release.Name }}-{{ .Values.db.volumeMounts.mysqlData.name }}-pv
