apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.dbService.name }}
  name: {{ .Release.Name }}-{{ .Values.dbService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.dbService.port }}
      protocol: {{ .Values.dbService.protocol }}
      targetPort: {{ .Values.dbService.targetPort }}
  selector:
    app: {{ .Release.Name }}-{{ .Values.db.name }}
  type: {{ .Values.dbService.type }}
